databases:
  - name: movie_review
    databaseName: movie_review
    user: movie_review
services:
  - type: web
    name: movie_review
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie_review
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false